// Stub /System/Library/Frameworks/AuthenticationServices.framework/Versions/A/AuthenticationServices for OS X 10.9.
// Generated by gen_framework_stub.py from the symbols real binaries bind.
// Classes exist so dyld can resolve the load; they intentionally do nothing.
#import <Foundation/Foundation.h>

// A stub class has to tolerate any selector a real caller uses. Declaring
// only the class would abort the process with "unrecognized selector" the
// first time one is called, so unknown selectors are forwarded to a no-op
// and return zero (nil / NO / 0). respondsToSelector: is left honest, so
// callers that feature-detect still take their unsupported path.
#define EH_STUB_FORWARDING \
    + (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    + (void)forwardInvocation:(NSInvocation *)invocation { } \
    - (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    - (void)forwardInvocation:(NSInvocation *)invocation { } \
    /* A stub must tolerate key-value coding as well as selectors. Callers \
     * configure these classes with setValue:forKey:, and KVC does not go \
     * through forwardInvocation: -- it raises instead, which is fatal: \
     *   this class is not key value coding-compliant for the key clear */ \
    - (void)setValue:(id)value forUndefinedKey:(NSString *)key { (void)value; (void)key; } \
    - (id)valueForUndefinedKey:(NSString *)key { (void)key; return nil; } \
    + (void)setValue:(id)value forUndefinedKey:(NSString *)key { (void)value; (void)key; } \
    + (id)valueForUndefinedKey:(NSString *)key { (void)key; return nil; }

#define STUB_CLASS(name) \
    @interface name : NSObject @end \
    @implementation name \
    EH_STUB_FORWARDING \
    @end

STUB_CLASS(ASAuthorizationController)
STUB_CLASS(ASAuthorizationPlatformPublicKeyCredentialDescriptor)
STUB_CLASS(ASAuthorizationPlatformPublicKeyCredentialProvider)
STUB_CLASS(ASAuthorizationPlatformPublicKeyCredentialRegistration)
STUB_CLASS(ASAuthorizationPublicKeyCredentialParameters)
STUB_CLASS(ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor)
STUB_CLASS(ASAuthorizationSecurityKeyPublicKeyCredentialProvider)
STUB_CLASS(ASAuthorizationSecurityKeyPublicKeyCredentialRegistration)
STUB_CLASS(ASCredentialIdentityStore)
STUB_CLASS(ASCredentialServiceIdentifier)
STUB_CLASS(ASPasswordCredentialIdentity)
STUB_CLASS(ASWebAuthenticationSession)

// Data constants. A caller may compare or log these, so where the real
// value is known it is reproduced exactly; otherwise the symbol names
// itself, which keeps it unique and greppable.
NSString * const ASAuthorizationPublicKeyCredentialAttestationKindDirect = @"ASAuthorizationPublicKeyCredentialAttestationKindDirect";
NSString * const ASAuthorizationPublicKeyCredentialResidentKeyPreferenceRequired = @"ASAuthorizationPublicKeyCredentialResidentKeyPreferenceRequired";
NSString * const ASAuthorizationPublicKeyCredentialUserVerificationPreferenceRequired = @"ASAuthorizationPublicKeyCredentialUserVerificationPreferenceRequired";
