// Stub AuthenticationServices.framework for OS X 10.9.
// Generated by gen-framework-stub.js from the symbols real binaries bind.
// Classes exist so dyld can resolve the load; they intentionally do nothing.
#import <Foundation/Foundation.h>

// A stub class has to tolerate any selector a real caller uses. Declaring
// only the class would abort the process with "unrecognized selector" the
// first time one is called, so unknown selectors are forwarded to a no-op
// and return zero (nil / NO / 0). respondsToSelector: is left honest, so
// callers that feature-detect still take their unsupported path.
#define EH_STUB_FORWARDING \
    + (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    + (void)forwardInvocation:(NSInvocation *)invocation { } \
    - (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    - (void)forwardInvocation:(NSInvocation *)invocation { }

#define STUB_CLASS(name) \
    @interface name : NSObject @end \
    @implementation name \
    EH_STUB_FORWARDING \
    @end

STUB_CLASS(ASWebAuthenticationSession)

// Credential-provider autofill. macOS has no extension point for it before
// 10.15, so the classes exist and do nothing; an app that registers identities
// finds none stored back.
STUB_CLASS(ASCredentialIdentityStore)
STUB_CLASS(ASCredentialServiceIdentifier)
STUB_CLASS(ASPasswordCredentialIdentity)
