// Stub /System/Library/Frameworks/CoreML.framework/Versions/A/CoreML for OS X 10.9.
// Generated by gen_framework_stub.py from the symbols real binaries bind.
// Classes exist so dyld can resolve the load; they intentionally do nothing.
#import <Foundation/Foundation.h>

// A stub class has to tolerate any selector a real caller uses. Declaring
// only the class would abort the process with "unrecognized selector" the
// first time one is called, so unknown selectors are forwarded to a no-op
// and return zero (nil / NO / 0). respondsToSelector: is left honest, so
// callers that feature-detect still take their unsupported path.
#define EH_STUB_FORWARDING \
    + (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    + (void)forwardInvocation:(NSInvocation *)invocation { } \
    - (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    - (void)forwardInvocation:(NSInvocation *)invocation { }

#define STUB_CLASS(name) \
    @interface name : NSObject @end \
    @implementation name \
    EH_STUB_FORWARDING \
    @end

STUB_CLASS(MLDictionaryFeatureProvider)
STUB_CLASS(MLFeatureValue)
STUB_CLASS(MLModel)
STUB_CLASS(MLModelConfiguration)
STUB_CLASS(MLMultiArray)
