// Stub /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth for OS X 10.9.
// Generated by gen_framework_stub.py from the symbols real binaries bind.
// Classes exist so dyld can resolve the load; they intentionally do nothing.
#import <Foundation/Foundation.h>

// A stub class has to tolerate any selector a real caller uses. Declaring
// only the class would abort the process with "unrecognized selector" the
// first time one is called, so unknown selectors are forwarded to a no-op
// and return zero (nil / NO / 0). respondsToSelector: is left honest, so
// callers that feature-detect still take their unsupported path.
#define EH_STUB_FORWARDING \
    + (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    + (void)forwardInvocation:(NSInvocation *)invocation { } \
    - (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \
    - (void)forwardInvocation:(NSInvocation *)invocation { }

#define STUB_CLASS(name) \
    @interface name : NSObject @end \
    @implementation name \
    EH_STUB_FORWARDING \
    @end

STUB_CLASS(CBCentralManager)
STUB_CLASS(CBManager)
STUB_CLASS(CBPeripheralManager)
STUB_CLASS(CBUUID)

// Data constants. A caller may compare or log these, so where the real
// value is known it is reproduced exactly; otherwise the symbol names
// itself, which keeps it unique and greppable.
NSString * const CBAdvertisementDataLocalNameKey = @"kCBAdvDataLocalName";
NSString * const CBAdvertisementDataServiceUUIDsKey = @"kCBAdvDataServiceUUIDs";
NSString * const CBCentralManagerOptionShowPowerAlertKey = @"kCBInitOptionShowPowerAlert";
NSString * const CBCentralManagerScanOptionAllowDuplicatesKey = @"kCBScanOptAllowDuplicates";
