#!/usr/bin/env python
"""
Generate stub/wrapper sources from frameworks.json.

Each entry names the symbols real binaries bind from a framework that 10.9
either lacks entirely ("stub") or ships without those symbols ("wrapper").
Only two symbol shapes are synthesised:

  _OBJC_CLASS_$_Name   a do-nothing class that tolerates any selector
  "constants" entries  an NSString * whose value comes from "values", falling
                       back to the symbol's own name

Nothing else is guessed. A symbol's name does not say whether it is a function
or a datum, so anything not covered above is reported for a human to implement
rather than synthesised -- a C function that no-ops and returns the wrong
answer is worse than a link error, because the caller cannot tell it failed.
Entries carrying "handwritten": true, and every "wrapper" entry, are skipped
outright; their source is maintained by hand.

Usage: gen_framework_stub.py [--out DIR] [name ...]
"""
import json, os, sys

HEADER = """// Stub %(fw)s for OS X 10.9.
// Generated by gen_framework_stub.py from the symbols real binaries bind.
// Classes exist so dyld can resolve the load; they intentionally do nothing.
#import <Foundation/Foundation.h>

// A stub class has to tolerate any selector a real caller uses. Declaring
// only the class would abort the process with "unrecognized selector" the
// first time one is called, so unknown selectors are forwarded to a no-op
// and return zero (nil / NO / 0). respondsToSelector: is left honest, so
// callers that feature-detect still take their unsupported path.
#define EH_STUB_FORWARDING \\
    + (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \\
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \\
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \\
    + (void)forwardInvocation:(NSInvocation *)invocation { } \\
    - (NSMethodSignature *)methodSignatureForSelector:(SEL)sel { \\
        NSMethodSignature *known = [super methodSignatureForSelector:sel]; \\
        return known ?: [NSMethodSignature signatureWithObjCTypes:"@@:@@@@@@@@"]; } \\
    - (void)forwardInvocation:(NSInvocation *)invocation { }

#define STUB_CLASS(name) \\
    @interface name : NSObject @end \\
    @implementation name \\
    EH_STUB_FORWARDING \\
    @end

"""

CLASS_PREFIX = "_OBJC_CLASS_$_"


def generate(name, entry):
    lines = [HEADER % {"fw": entry.get("framework", name)}]
    classes, consts, unknown = [], [], []
    declared_constants = set(entry.get("constants", []))
    for sym in sorted(entry.get("symbols", [])):
        if sym.startswith(CLASS_PREFIX):
            classes.append(sym[len(CLASS_PREFIX):])
        elif sym in declared_constants:
            consts.append(sym[1:])
        elif sym.startswith("_$s"):
            unknown.append((sym, "Swift mangled symbol"))
        else:
            unknown.append((sym, "not declared in \"constants\""))
    for c in classes:
        lines.append("STUB_CLASS(%s)\n" % c)
    if consts:
        values = entry.get("values", {})
        lines.append("\n// Data constants. A caller may compare or log these, so where the real\n"
                     "// value is known it is reproduced exactly; otherwise the symbol names\n"
                     "// itself, which keeps it unique and greppable.\n")
        for c in consts:
            lines.append('NSString * const %s = @"%s";\n' % (c, values.get(c, values.get("_" + c, c))))
    if unknown:
        sys.stderr.write("%s: %d symbol(s) NOT generated -- needs a hand-written implementation:\n" % (name, len(unknown)))
        for sym, why in unknown:
            sys.stderr.write("    %-70s %s\n" % (sym, why))
    return "".join(lines), len(unknown)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    args = [a for a in sys.argv[1:]]
    outdir = here
    if "--out" in args:
        i = args.index("--out")
        outdir = args[i + 1]
        del args[i:i + 2]
    spec = json.load(open(os.path.join(here, "frameworks.json")))
    wanted = args or sorted(spec)
    rc = 0
    for name in wanted:
        entry = spec.get(name)
        if entry is None:
            sys.stderr.write("no such framework in frameworks.json: %s\n" % name)
            rc = 1
            continue
        if entry.get("handwritten"):
            print("%-28s skipped (hand-written)" % name)
            continue
        if entry.get("kind") != "stub":
            print("%-28s skipped (%s -- hand-written by nature)" % (name, entry.get("kind")))
            continue
        src, nunknown = generate(name, entry)
        path = os.path.join(outdir, entry.get("source", name + "Stub.m"))
        if os.path.exists(path) and "Hand-written" in open(path).read():
            print("%-28s skipped (existing file marked Hand-written)" % name)
            continue
        open(path, "w").write(src)
        print("%-28s -> %s%s" % (name, os.path.basename(path),
                                 "" if not nunknown else "  (%d symbol(s) left out)" % nunknown))
    return rc


if __name__ == "__main__":
    sys.exit(main())
